### PR TITLE
Add back/forward browser history for navigation in the Customizer preview

### LINKED ISSUE #2: Use pushState when preview URL changed
See https://github.com/xwp/wp-customizer-browser-history/blob/a68c70bd9101a2e7dd24ee040a05d4cec37cb11a/customizer-browser-history.js#L77-L112

On `popstate` we'd need to make sure that we only update the `url` and leave the autofocus params intact.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #2

### CODE REVIEW

**Comment by westonruter** [comment]
@fjarrett would you like to try this out?

**Comment by frankiejarrett** [comment]
@westonruter I'd love to but I'm not sure what it does yet...

**Comment by westonruter** [comment]
@fjarrett it allows you to use the browser's back and forward buttons to effect the URL being previewed. So you can click a link in the preview, and then click back to go to the previous URL.

**Comment by frankiejarrett** [comment]
😻 😻 😻 😻 😻 This is working awesome! Great success.

**Comment by westonruter** [comment]
Thanks for testing!

**Pull request merged**
